// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class user_removed_pswd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_removed_pswd));
        
        string IMigrationMetadata.Id
        {
            get { return "201310300935283_user_removed_pswd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
