// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class discussion_tag : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(discussion_tag));
        
        string IMigrationMetadata.Id
        {
            get { return "201311050926452_discussion_tag"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
