// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updated_msg_receiver : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updated_msg_receiver));
        
        string IMigrationMetadata.Id
        {
            get { return "201310181447020_updated_msg_receiver"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
