// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class update_user_roleStr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_user_roleStr));
        
        string IMigrationMetadata.Id
        {
            get { return "201311290548563_update_user_roleStr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
