// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class added_notify_user : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_notify_user));
        
        string IMigrationMetadata.Id
        {
            get { return "201310281421292_added_notify_user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
