// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addCurrentEJob : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addCurrentEJob));
        
        string IMigrationMetadata.Id
        {
            get { return "201309230714552_addCurrentEJob"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
