// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class update_userlog_01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_userlog_01));
        
        string IMigrationMetadata.Id
        {
            get { return "201312110754274_update_userlog_01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
