// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class added_jobOpening_02 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_jobOpening_02));
        
        string IMigrationMetadata.Id
        {
            get { return "201311140709251_added_jobOpening_02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
