// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updated_joOpen_expNUll : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updated_joOpen_expNUll));
        
        string IMigrationMetadata.Id
        {
            get { return "201311190449430_updated_joOpen_expNUll"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
