// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class added_serviceinfo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_serviceinfo));
        
        string IMigrationMetadata.Id
        {
            get { return "201312151205594_added_serviceinfo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
