// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class UserCourse_Update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserCourse_Update));
        
        string IMigrationMetadata.Id
        {
            get { return "201310011332103_UserCourse_Update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
