// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updated_userMap_userName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updated_userMap_userName));
        
        string IMigrationMetadata.Id
        {
            get { return "201310210718462_updated_userMap_userName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
