// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class added_Circles_DBCxt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_Circles_DBCxt));
        
        string IMigrationMetadata.Id
        {
            get { return "201310170522442_added_Circles_DBCxt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
