// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class jobPost_update_desiredSkill : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(jobPost_update_desiredSkill));
        
        string IMigrationMetadata.Id
        {
            get { return "201311170914317_jobPost_update_desiredSkill"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
