// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class added_userrolecode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_userrolecode));
        
        string IMigrationMetadata.Id
        {
            get { return "201311111205494_added_userrolecode"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
