// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updated_specialOffer_11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updated_specialOffer_11));
        
        string IMigrationMetadata.Id
        {
            get { return "201312111640021_updated_specialOffer_11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
