// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updated_email : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updated_email));
        
        string IMigrationMetadata.Id
        {
            get { return "201311130721006_updated_email"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
