// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class UserCouse_Add : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserCouse_Add));
        
        string IMigrationMetadata.Id
        {
            get { return "201310011327075_UserCouse_Add"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
