// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class update_news : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_news));
        
        string IMigrationMetadata.Id
        {
            get { return "201311281310547_update_news"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
