// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class update_news_anonymos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_news_anonymos));
        
        string IMigrationMetadata.Id
        {
            get { return "201312060651167_update_news_anonymos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
