// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updated_user_volunteer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updated_user_volunteer));
        
        string IMigrationMetadata.Id
        {
            get { return "201312211439052_updated_user_volunteer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
