// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class added_failedloginsd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_failedloginsd));
        
        string IMigrationMetadata.Id
        {
            get { return "201311130729034_added_failedloginsd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
