// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updated_msgLength : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updated_msgLength));
        
        string IMigrationMetadata.Id
        {
            get { return "201311190727453_updated_msgLength"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
