// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updated_msgUserMap_notify : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updated_msgUserMap_notify));
        
        string IMigrationMetadata.Id
        {
            get { return "201310200923114_updated_msgUserMap_notify"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
