// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class added_user_intersts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_user_intersts));
        
        string IMigrationMetadata.Id
        {
            get { return "201310081102040_added_user_intersts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
