// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class removed_user_contact_visibility : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removed_user_contact_visibility));
        
        string IMigrationMetadata.Id
        {
            get { return "201310131357232_removed_user_contact_visibility"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
