// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updated_disc_deletion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updated_disc_deletion));
        
        string IMigrationMetadata.Id
        {
            get { return "201312150357493_updated_disc_deletion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
