// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class user_digest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_digest));
        
        string IMigrationMetadata.Id
        {
            get { return "201312131216390_user_digest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
