// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updates_msg_totally : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updates_msg_totally));
        
        string IMigrationMetadata.Id
        {
            get { return "201310181653184_updates_msg_totally"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
