// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class testingRevert : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(testingRevert));
        
        string IMigrationMetadata.Id
        {
            get { return "201310010619482_testingRevert"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
