// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updated_jobpost_resume : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updated_jobpost_resume));
        
        string IMigrationMetadata.Id
        {
            get { return "201311211110534_updated_jobpost_resume"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
