// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updated_Connect_CourseDetails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updated_Connect_CourseDetails));
        
        string IMigrationMetadata.Id
        {
            get { return "201310100809458_updated_Connect_CourseDetails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
