// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updated_Connect_DateNUll : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updated_Connect_DateNUll));
        
        string IMigrationMetadata.Id
        {
            get { return "201310100412031_updated_Connect_DateNUll"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
