// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class added_discussion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_discussion));
        
        string IMigrationMetadata.Id
        {
            get { return "201310290601199_added_discussion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
