// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addedFamily_ : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedFamily_));
        
        string IMigrationMetadata.Id
        {
            get { return "201309240422378_addedFamily_"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
