// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class common_threadIte : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(common_threadIte));
        
        string IMigrationMetadata.Id
        {
            get { return "201310310742572_common_threadIte"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
