// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updatedUser_IsAdminCreated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedUser_IsAdminCreated));
        
        string IMigrationMetadata.Id
        {
            get { return "201311261156134_updatedUser_IsAdminCreated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
