// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updated_toknow_ip_01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updated_toknow_ip_01));
        
        string IMigrationMetadata.Id
        {
            get { return "201312071410375_updated_toknow_ip_01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
