// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addedNameMsg : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedNameMsg));
        
        string IMigrationMetadata.Id
        {
            get { return "201310070551240_addedNameMsg"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
