// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class update_alumnitoKnow_02 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_alumnitoKnow_02));
        
        string IMigrationMetadata.Id
        {
            get { return "201311251239068_update_alumnitoKnow_02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
