// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class jobPost_updateTime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(jobPost_updateTime));
        
        string IMigrationMetadata.Id
        {
            get { return "201311200701308_jobPost_updateTime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
