// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updated_event_picsurl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updated_event_picsurl));
        
        string IMigrationMetadata.Id
        {
            get { return "201312170530272_updated_event_picsurl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
