// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updated_reltion_withUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updated_reltion_withUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201312011313199_updated_reltion_withUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
