// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class removedUserBatch : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedUserBatch));
        
        string IMigrationMetadata.Id
        {
            get { return "201310031045458_removedUserBatch"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
