// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updated_alumniknow_Speak : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updated_alumniknow_Speak));
        
        string IMigrationMetadata.Id
        {
            get { return "201311251224283_updated_alumniknow_Speak"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
