// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updated_edu_batch : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updated_edu_batch));
        
        string IMigrationMetadata.Id
        {
            get { return "201401080420114_updated_edu_batch"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
