// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Blog_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Blog_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201402040647030_Blog_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
