// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class tweet_aff : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tweet_aff));
        
        string IMigrationMetadata.Id
        {
            get { return "201401270535287_tweet_aff"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
