// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class chapter_added_fburl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(chapter_added_fburl));
        
        string IMigrationMetadata.Id
        {
            get { return "201408191453044_chapter_added_fburl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
