// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class added_chapter : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_chapter));
        
        string IMigrationMetadata.Id
        {
            get { return "201407050754544_added_chapter"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
