// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class update_disc_content_req : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_disc_content_req));
        
        string IMigrationMetadata.Id
        {
            get { return "201402021527576_update_disc_content_req"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
