// <auto-generated />
namespace Axb.ActiveAlumni.Nit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updated_chapter_head : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updated_chapter_head));
        
        string IMigrationMetadata.Id
        {
            get { return "201407070551513_updated_chapter_head"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
